### PR TITLE
Add TryGetAttribute.

### PR DESCRIPTION
**Pull request by jirisykora83**
Extend API with TryGetAttribute.

### CODE REVIEW

**Comment by jirisykora83** [comment]
@osjoberg Do you have time to marge this? Or it's some issue with this pull request?

**Comment by osjoberg** [comment]
@jirisykora83 thanks for the pull request! I have been too busy to do anything. It looks good, however my plan was to see if TryGetAttribute could call GetAttribute instead of repeating the logic and also run benchmarks to see if the AggressiveInlining would make any performance benefit.

**Comment by jirisykora83** [comment]
Ok thank you so much for your response. If you start with benchmarking inlining maybe it will be nice try to move throwing path to seperte method because if i am not wrong if method throwing exception then it is not possible to inlining (even force with attribute).

Example: [corefx - Improve performance for Math.Abs](https://github.com/dotnet/corefx/commit/4c2b1895cc9982a8f39b8f2c64ffbb5f684ed3d3) use "ThrowAbsOverflow();" helper method for avoid throw in method which shoud be inlining.

**Comment by SebastianStehle** [comment]
I would just close that.

**Pull request closed without merging**
