### PR TITLE
Massive performance improvements

### PR DESCRIPTION
**Pull request by SebastianStehle**
Hi,

I made few performance improvements:

1. Provide access to texts via ReadOnlyMemory<char> for .NET. Avoids the allocation.
2. Use a object pool for the state machine.
3. Ensure that we do not create a new instance of the state delegate each time (saves hundreds of MB).

```
|               Method |   Job | BuildConfiguration |              Mean |              Error |           StdDev | Ratio | RatioSD |      Gen0 |     Gen1 |     Gen2 |  Allocated | Alloc Ratio |
|--------------------- |------ |------------------- |------------------:|-------------------:|-----------------:|------:|--------:|----------:|---------:|---------:|-----------:|------------:|
|         ExtractLinks | 0.8.1 |             V0_8_1 | 18,939,931.771 ns | 110,563,744.565 ns | 6,060,371.920 ns |  1.56 |    0.38 | 1578.1250 | 265.6250 |  15.6250 | 19833903 B |       12.54 |
|         ExtractLinks |   Dev |            Default | 12,202,738.021 ns |  48,285,226.010 ns | 2,646,676.169 ns |  1.00 |    0.00 |  125.0000 | 109.3750 |        - |  1581549 B |        1.00 |
|                      |       |                    |                   |                    |                  |       |         |           |          |          |            |             |
| ExtractLinksAsMemory | 0.8.1 |             V0_8_1 |          8.046 ns |          31.033 ns |         1.701 ns | 0.000 |    0.00 |    0.0025 |        - |        - |       32 B |       0.000 |
| ExtractLinksAsMemory |   Dev |            Default | 16,508,651.042 ns |  47,748,024.022 ns | 2,617,230.315 ns | 1.000 |    0.00 |   78.1250 |  31.2500 |  31.2500 |  1056482 B |       1.000 |
|                      |       |                    |                   |                    |                  |       |         |           |          |          |            |             |
|         ExtractTexts | 0.8.1 |             V0_8_1 | 22,844,795.833 ns |  73,189,047.011 ns | 4,011,738.632 ns |  2.24 |    0.41 | 1656.2500 | 859.3750 | 562.5000 | 21347591 B |        6.90 |
|         ExtractTexts |   Dev |            Default | 10,201,960.417 ns |   1,196,800.986 ns |    65,600.700 ns |  1.00 |    0.00 |  234.3750 | 218.7500 | 109.3750 |  3095085 B |        1.00 |
|                      |       |                    |                   |                    |                  |       |         |           |          |          |            |             |
| ExtractTextsAsMemory | 0.8.1 |             V0_8_1 |          8.603 ns |          20.684 ns |         1.134 ns | 0.000 |    0.00 |    0.0025 |        - |        - |       32 B |       0.000 |
| ExtractTextsAsMemory |   Dev |            Default |  9,114,607.292 ns |   1,768,497.946 ns |    96,937.340 ns | 1.000 |    0.00 |  281.2500 | 281.2500 | 281.2500 |  1259213 B |       1.000 |
 ```
 
 I have updated the benchmarks to be able to compare different versions. The difference is so huge, that I am not sure yet, if I have broken something. But the tests are green.
 
 There is still room for improvement.
 
 1. Perhaps the linked list in the buffer reader can be replaced with a stack or so and then pooled as well.
 2. The peek method in the buffer reader allocates memory. Perhaps it can be replaced with an internal char buffer and then using ReadOnlyMemory<char> internally.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Okay, something is broken. I knew that it would be too good :

EDIT: The EOF marker was not reset in the pool :D ... I updated the benchmark. Still looks good.

**Comment by SebastianStehle** [comment]
I also improved the buffer reader. The only allocation that is left is the LinkedList.

**Comment by SebastianStehle** [comment]
I also fixed the linkedlist. So there should be no more allocations.

image

* The strings are from the text properties, which also are not needed if you use `ReadonlyMemory<char>`
* The arrays are from the tests

=> ZERO ALLOCATION PARSING

**Comment by SebastianStehle** [comment]
@osjoberg 

I fixed all the tests and found a minor bug, but I am not sure if it is in your code or my code:

1. I think we also have to update the line number if we read from the peek buffer: https://github.com/osjoberg/HtmlPerformanceKit/blob/master/HtmlPerformanceKit/Infrastructure/BufferReader.cs#L74
2. I think we should not update the line number if we read a negative value.

**Comment by osjoberg** [comment]
@SebastianStehle thank you for your contributions. Great improvements, I will probably add most if not all of your suggestions but I cannot merge as-is because the change set is a bit large and hard for me to overview.

Regarding the line number / characer position I initially wanted it to be exact but I was not able to make it 100% correct so in the end I opted for a simple solution that will get it mostly right. However not handling EOF is an oversight.

**Comment by SebastianStehle** [comment]
Let me know if I can do something to make your life easier. Most of the files are changed because I had to fix the construction of delegates. So 70% of the files is exactly the same change.

**Comment by osjoberg** [comment]
Thank you! I have incorporated most of your suggestions, here are my notes:

- `BufferReader` needs to support adding items both in the start of the buffer and in the end of the buffer, that is why `LinkedList` was previously used and why `Stack` and `Queue` is not really working. I implemented a `QueueStack` data structure which is backed by an array yielding some more performance as well. Unfortenuately there is no test that catches this, which is why i guess you missed it.

- While the public `*AsMemory` function and property certainly saves memory and yields a little bit better performance it will be dangerous; if you save a reference to a `Memory` and advance the reader by calling `Read()`, the underlying data that the `Memory` refers to will be changed. Will the average user understand this behaviour?

- The pooling of the state machine adds a lot of complexity in that there may be subtle errors that I feel will be difficult to properly test for. If I weigh the added complexity to what the gains are in improved memory usage, my conclusion at this point is that it is not worth it. 

A new nuget package was released, v0.9.

**Comment by SebastianStehle** [comment]
Thanks:

1. Yes, I have noticed it as well. I have therefore used 2 buffers that can be pooled.

2. Really depends on the use case. I have a use case where I extract the texts from html. So basically html -> text converter. In this case I can copy the memory output directly to a StringBuffer and I have no need for the strings. But in another use case I thought I could use that, but it was not possible. But the library is a low level abstraction layer anyway, so I think it is fine.

3. Up to you. I have created a fork for my mjml library and it works perfectly fine. I thought that the goal of such a library is also learning and to push it to the limits.

**Comment by osjoberg** [comment]
Just a heads up; I think your implementation of BufferReader differs from the original in the following ways:

`BufferReader.Reconsume()` Should add to the beginning of the buffer, not the end
`BufferReader.Peek()` Does not take the `reconsumeBuffer` into consideration as I believe it should
`BufferReader.Peek(int length)` Does not take the `reconsumeBuffer` into consideration as I believe it should

Are theese changes in functionality intended? No tests seems to be broken and maybe there might be no changes for the majority of HTML input. My intent was to follow the spec as far as understood it. Given my original interpretation was correct in this regard the changes noted above might lead to a different result.

**Comment by SebastianStehle** [comment]
I am not entirely sure about these changes, tbh, but I like your change as well. The goal was to have a fixed allocation and you also achieved it :)

I was never that confident about the changes to the BufferReader, because there are no tests and I am not sure about whether there are any scenarios that reconsume more than one character.

**Comment by SebastianStehle** [comment]
It would be really great to have the ReadOnlyMemory endpoints in the code. As I said, I think your library is mainly used by people doing low level stuff, everybody else uses other libraries like AngleSharp.

**Pull request closed without merging**
